title: Nat Neale
author: NN
email: nataliehneale@gmailcom
description: > # this means to ignore newlines until "baseurl:"
  hello internet!

# social links
twitter_username: nathuntneale
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
