title: Nat Neale
author: NN
email: nataliehneale@gmailcom
description: hello internet!

# social links
twitter_username: nathuntneale
github_username:  nneale

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima

date: 05/30/20
